### ISSUE TITLE
Asm blocks contains instructions twice

### ISSUE THREAD

**Issue by ggqb** [cea-sec/miasm#100]
Hi,

I think [this line](https://github.com/cea-sec/miasm/blob/master/miasm2/ir/ir.py#L212). should be removed (or not). 

When using the jitter, if we print the content of: 
**sb.jitter.ir_arch.get_bloc(addr).lines** 
we can see the instructions are present twice. It is because it is also appended to the **lines** array [here](https://github.com/cea-sec/miasm/blob/master/miasm2/ir/ir.py#L228).

EDIT: By removing the line, it seems to make Miasm to crash here : 
**assert len(irbloc.irs) == len(irbloc.lines)**. 

gg.

**Comment by serpilliere** [comment]
Hi
This is *currently* an expected behavior. In fact, the `ir` list and the `lines` list *must* have the same length because some internal Miasm algorithms make this assumption. So this line is here to keep those lists 'synchronized'. This is fucking crappy (see `REP MOVSB`).

We (with @commial) are currently designing a class that will represent an IR block, which should make its manipulation easier, and avoid such strange results.

For instance, the synchronization can allow one to track back assembly lines from IR form.
