### ISSUE TITLE
Jitter: endianness for GCC and LLVM on macOS

### ISSUE THREAD

**Issue by icecr4ck** [cea-sec/miasm#1038]
Hello,

I tried to use the DSE on a x86-64 binary and I got this strange DriftException:
```
miasm.analysis.dse.DriftException: Drift of @64[0x13FFD0]: 1898898676 instead of 17646280302810628096
```

This happens when the instruction `PUSH 0x712EE4F4` is handled by the DSE and as you can see in the exception error, it looks more like an endianness issue:
* `hex(1898898676) = 0x712EE4F4`
* `hex(17646280302810628096) = 0xF4E42E7100000000` 

So I investigate a bit and the problem seems to come from this part of the code:
https://github.com/cea-sec/miasm/blob/4c2320b46250a8d6f8774e1218544b72a154cd8e/miasm/analysis/dse.py#L301-L308

Removing the `[::-1]` in `int(encode_hex(value_chr[::-1]), 16)` resolves the issue, however this is not the behaviour expected as x86 is a little endian architecture.

Also, looking at the following result makes me think the data is not stored correctly in memory as I get:
```
>>> data = sb.jitter.vm.get_mem(0x13FFD0, 8)
'\x00\x00\x00\x00q.\xe4\xf4'
>>> hex(unpack('<Q', sb.jitter.vm.get_mem(0x13FFD0, 8))[0])
'0xf4e42e7100000000'
```
And if I'm not mistaken, I should get:
```
>>> data = sb.jitter.vm.get_mem(0x13FFD0, 8)
'\xf4\xe4.q\x00\x00\x00\x00'
>>> hex(unpack('<Q', sb.jitter.vm.get_mem(0x13FFD0, 8))[0])
'0x712ee4f4'
```

Am I completely wrong (which is strongly possible) or is there a real issue?

Thanks!

**Comment by commial** [comment]
Hi,

So, just to explain it a bit more:
* indeed, the DSE engine makes the assumption the target architecture is little endian (as the Symbolic execution engine)
* a `DriftException` happens when the concrete and the symbolic execution does not finish with the same result / state
* the symbolic execution never writes to the memory (https://github.com/cea-sec/miasm/blob/master/miasm/analysis/dse.py#L137, https://github.com/cea-sec/miasm/blob/master/miasm/analysis/dse.py#L154). It's read-only, and it's the role of the concrete exec to update the memory


So, at the end, if the state in memory (`sb.jitter.vm`) does not reflect what you expected, it's probably an error in the concrete execution or in a stub written by the user.
You could probably highlight this by removing the DSE part and inspecting your memory having just the concrete execution.

Do not hesitate, if we can help to investigate further

**Comment by icecr4ck** [comment]
Ok thanks, I made some tests with the jitter only and everything went well, after the`PUSH 0x712EE4F4` (first instruction of the binary), I got the expected result (0x712EE4F4 is stored in little endian).
```
>>> data = sb.jitter.vm.get_mem(0x13FFD0, 8)
'\xf4\xe4.q\x00\x00\x00\x00'
>>> hex(unpack('<Q', sb.jitter.vm.get_mem(0x13FFD0, 8))[0])
'0x712ee4f4'
```

What I don't understand is, when I add the DSE, the dword 0x712EE4F4 seems to be stored in big endian in the concrete execution, and thus the DriftException happens.

**Comment by wzrybuddy** [comment]
Hi, if you use debug mode run your script, maybe you can see what diffrence when add the DSE.

because jitter engine execute instr one by one, and the order is Symbolic first, then jitter instr, so if you add breakpoint at last instr, before DriftException raise,  you can compare Symbolic result and jitter result.

**Comment by icecr4ck** [comment]
Ok, so I investigated a bit more and it seems that depending on the jitter used, the endianness is not correctly handled. Basically if you run the following script, you get 2 different results.
```
from binascii import hexlify

from miasm.analysis.machine import Machine
from miasm.core.locationdb import LocationDB
from miasm.jitter.csts import PAGE_READ, PAGE_WRITE

def code_sentinelle(jitter):
    jitter.run = False
    jitter.pc = 0
    return True

machine = Machine('x86_32')
loc_db = LocationDB()
mn = machine.mn

l = mn.fromstring('PUSH 0x1337BEEF', loc_db, 32)
a = mn.asm(l)[0]

jitter_gcc = machine.jitter('gcc')
jitter_python = machine.jitter('python')

jitter_gcc.init_stack()
jitter_python.init_stack()

jitter_gcc.vm.add_memory_page(0, PAGE_READ | PAGE_WRITE, a)
jitter_python.vm.add_memory_page(0, PAGE_READ | PAGE_WRITE, a)

# to stop the execution once the push instruction is jitted
jitter_gcc.add_breakpoint(5, code_sentinelle)
jitter_python.add_breakpoint(5, code_sentinelle)

jitter_gcc.init_run(0)
jitter_python.init_run(0)

jitter_gcc.continue_run()
jitter_python.continue_run()

print(hexlify(jitter_gcc.vm.get_mem(jitter_gcc.cpu.ESP, 4)))
print(hexlify(jitter_python.vm.get_mem(jitter_python.cpu.ESP, 4)))
```
The GCC jitter stores the dword in memory in big endian order and the Python jitter stores it in little endian order. I did some tests with the LLVM jitter, and it stores the dword in big endian too.

**Comment by wzrybuddy** [comment]
Hi @icecr4ck , i run you script, but get 2 same result. i have no idea why your result is different 

if you use gcc gitter, maybe you could breakpoint at follow line

https://github.com/cea-sec/miasm/blob/4c2320b46250a8d6f8774e1218544b72a154cd8e/miasm/jitter/jitcore_gcc.py#L54

when jitter translate IR to C code, if you find the push immediate not equr in the C code, i think the problem is about compile.

**Comment by serpilliere** [comment]
Hey guys!
Just to be sure: If you modify instruction semantics or jitter funtions, you must be sure there is no more 'cache' files remaining in `/tmp/miasm_cache`.
If so, the jitter will keep "old" code and your modifications won't be used.

**Comment by icecr4ck** [comment]
Alright, I think I have identified the problem. I should have mentioned that I'm using Miasm on macOS...

It seems this is because of #1017. The associated commit adds some definitions in the `miasm/jitter/vm_mngr.h` file to fix the build on macOS.

Basically, if I replace:
```c
#ifdef __APPLE__
#define __BYTE_ORDER __BYTE_ORDER__
#ifndef __BIG_ENDIAN
#define __BIG_ENDIAN '>'
#define __LITTLE_ENDIAN '<'
#endif
```
by
```c
#ifdef __APPLE__
#define __BYTE_ORDER __BYTE_ORDER__
#define __BIG_ENDIAN BIG_ENDIAN
#define __LITTLE_ENDIAN LITTLE_ENDIAN
```
it fixes the endianness problem and it still builds like a charm.

**Comment by serpilliere** [comment]
Great!
Can you PR this @icecr4ck ?

**Comment by icecr4ck** [comment]
Done :)
