### ISSUE TITLE
High level operators are not implemented in the llvmconverter

### ISSUE THREAD

**Issue by nofiv** [cea-sec/miasm#1042]
Hi, I've just noticed that the high level operators are not implemented in the llvmconverter yet and hence perhaps "COND_NE" raises the NotImplementedError() at [llvmconvert.py](https://github.com/cea-sec/miasm/blob/master/miasm/jitter/llvmconvert.py#L1208). Shall I try to implement it or is there anything in progress?

**Comment by commial** [comment]
Hi, indeed there aren't implemented. This is because the llvm convert was only used for the jitter needs, which receive an IR with high level operator already transformed to their explicit form.

But it may be missing for a few of the recent operators, like equality, inequality, signed and unsigned comparison.
