### ISSUE TITLE
dst in IR CFG is not set for blocks that end with CALL

### ISSUE THREAD

**Issue by htfy96** [cea-sec/miasm#1086]
Code:
```c
int sum_of_two_calls(int (*fn)(void)) {
    return fn() + fn();
}
```

```
$ objdump -dSC break-flow.so
0000000000001000 <sum_of_two_calls>:
    1000:	55                   	push   %rbp
    1001:	48 89 e5             	mov    %rsp,%rbp
    1004:	53                   	push   %rbx
    1005:	48 83 ec 18          	sub    $0x18,%rsp
    1009:	48 89 7d e8          	mov    %rdi,-0x18(%rbp)
    100d:	48 8b 45 e8          	mov    -0x18(%rbp),%rax
    1011:	ff d0                	callq  *%rax
    1013:	89 c3                	mov    %eax,%ebx
    1015:	48 8b 45 e8          	mov    -0x18(%rbp),%rax
    1019:	ff d0                	callq  *%rax
    101b:	01 d8                	add    %ebx,%eax
    101d:	48 83 c4 18          	add    $0x18,%rsp
    1021:	5b                   	pop    %rbx
    1022:	5d                   	pop    %rbp
    1023:	c3                   	retq
```

In ASM CFG, the dsts of the two blocks containing CALL instruction are set to the subsequent block:
![Screenshot from 2019-11-01 20-42-36](https://user-images.githubusercontent.com/8121231/68065544-28491080-fce8-11e9-8d55-1b09af83a77b.png)

However, in IR CFG, no block has its dst set:
![Screenshot from 2019-11-01 20-44-14](https://user-images.githubusercontent.com/8121231/68065566-61818080-fce8-11e9-884a-c4706ffb7188.png)

**Comment by serpilliere** [comment]
Hi!
If you are using `full.py`, you are looking at the `graph_irflow_raw.dot` which is the raw IR of the of the basic blocks.
To have a the IR graph of the function, you have to graph `graph_irflow.dot`

To see the diffrence you can use `full.py` in the example:
```
python miasm/example/disasm/full.py  -m x86_64  -g sum.bin
```

```
xdot graph_irflow_raw.dot
```
gives:
![graph_irflow_raw](https://user-images.githubusercontent.com/9433661/68074486-c0ec9880-fd9b-11e9-8362-45758e8ee5d7.png)


and 
```
xdot graph_irflow_raw.dot
```

gives:
![graph_irflow](https://user-images.githubusercontent.com/9433661/68074482-b3371300-fd9b-11e9-8324-1d50fe050f1e.png)


In the first case the IR code of the call is the *real* sides effects of the instruction `call`
In the second case, the call is "modeled" using special operarands `cal_xxx`.

Note that to be usefull and correct, the user (you :smile: ) have to subclass the `call_effects` in your script in order to match your needs during IR analysis. The default model is a "dummy" one. For example here, we concider the x86 64 ABI which always takes 4 arguments (set in RCX RDX R8 R9)

I hope this is a bit clearer!

**Comment by htfy96** [comment]
Thanks for the advise. call_effects makes sense to me
