### ISSUE TITLE
miasm vs miasm2 question

### ISSUE THREAD

**Issue by PavelKotov1** [cea-sec/miasm#1164]
Bonjour mes amis!
I wonder if somebody would be so kind to answer my question.
I have successfully downloaded and installed miasm and trying to learn how to use it. 
In the sources i see things like this (for example):
from miasm.analysis.machine import Machine.
In the BlackHat presentation: "Miasm2. Reverse engineering framework" F. Desclaux, C. Mougey 
(https://i.blackhat.com/us-18/Wed-August-8/us-18-DesclauxMougey-Miasm-Reverse-Engineering-Framework.pdf) use **miasm2**. 
For example: from **miasm2** . a n a l y s i s . b i n a r y i m p o r t C o n t a i n e r
So, what is the difference between the two? I could not find separate source download for miasm2.
The only thing i found was Miasm2-Docker Automated build for Miasm2 ((https://github.com/serpilliere/miasm-docker). )
Containers descriptions "Miasm2" fully functionnal build (_Sources_). but the hyperlink from Sources on that page leads to https://code.google.com/archive/p/miasm/. 
That page contains instructions:
Obtain Miasm: clone repo: http://code.google.com/p/miasm/ 
 hg clone https://code.google.com/p/miasm/ but this is obviously not a valid hg depository and leads back to itself. So much for that!
Sorry for the possibly confusing post, but to put it plainly: where and how could one get his hands on **miasm2**?

Merci bien!

**Comment by XVilka** [comment]
https://github.com/cea-sec/miasm/commit/944806c506446c918eb74c17a605f5f56d4b75e0

**Comment by serpilliere** [comment]
Hi!
Note that the whole site `code.google.com` is deprecated since many years. That's why is you click on the link you have provided, (http://code.google.com/p/miasm/) it's now redirected to https://code.google.com/archive/p/miasm/

We definitely renamed the `miasm2` project to `Miasm`, and we are using classic version numbers in this project: see https://github.com/cea-sec/miasm/releases
I must admit we did some errors in the first publications of the source code. But it is getting cleaner :smile: 
Note that we have a working pip package as well: https://pypi.org/project/miasm/

**Comment by PavelKotov1** [comment]
Thank you for your kind words! 
My faulty assumption was that miasm2 had come out AFTER miasm, which was obviously wrong, hence the confusion.
Now, thanks to you, it all fell into proper place!
Thanks again!

**Comment by serpilliere** [comment]
No problemo @PavelKotov1 : this is due to the incredible mess we did during the firsts releases :beer:

**Comment by PavelKotov1** [comment]
>>the incredible mess
saloperie de mess! sacré Nom!
My street French is heavily based on the vocabulary of Chevalier D'Artagnan (XVII ciecle) and is a bit dated...
