### ISSUE TITLE
suggestion: increase TranslatorC.NATIVE_INT_MAX_SIZE depending on platform

### ISSUE THREAD

**Issue by tly000** [cea-sec/miasm#1365]
gcc supports `uint128_t`  on x64 targets and clang 11 or higher supports basically any `uintX_t` via the `_ExtInt(X)` feature (see https://blog.llvm.org/2020/04/the-new-clang-extint-feature-provides.html). This means that `bn_t` can be avoided in a lot of cases. The main problem with this is the missing numeric literal support for these types.

**Comment by serpilliere** [comment]
Hi @tly000 ,
Hey, this is really interesting, and we weren't aware of this.
For now, we have some x86 32 bit targets, as well as arm (in order to run Miasm on phones) so maybe we will keep the bn_t support.

But yes, the idea to remove the bn_t in clang for _ExtInt seems interesting.
Thank you for the the hint @tly000 !

**Comment by tly000** [comment]
i currently use miasm for a project where i convert ircfg functions to c functions with the type `void(vm_cpu*)`. I use a slightly modified TranslatorC and it seems to work quite well 🙂 the only problem with this approach is the performance, this is why i locally removed the `bn_t`.
