### ISSUE TITLE
miasm in Rust #2

### ISSUE THREAD

**Issue by qynybary-ryteto** [cea-sec/miasm#1463]
I am writing to inquire about the plans for implementing a Rust version of miasm. There has been mention of work on this in the comments of issues, such as in:
https://github.com/cea-sec/miasm/issues/1197#issuecomment-619946840
https://github.com/cea-sec/miasm/issues/1197#issuecomment-621058107
https://github.com/cea-sec/miasm/issues/1366#issuecomment-830594769
https://github.com/cea-sec/miasm/issues/1411
https://github.com/cea-sec/miasm/issues/1404#issuecomment-1273561707

where @serpilliere indicated that work on the Rust version of miasm was ongoing and a public release was planned after some code cleaning and improvements.

I would greatly appreciate any information on the current status of this project. Specifically, I am interested in:

1. Is work on the Rust version of miasm still ongoing?
2. If so, what are the future plans, particularly regarding the estimated timeline for the release of this version?
3. Is there an opportunity to contribute to the development or assist in other ways?

Thank you for any information you can provide on this matter

**Comment by serpilliere** [comment]
Hi @qynybary-ryteto 

There is version of Miasm is rust (miasm-rs)
This version is not public for the moment, but most people who have requested have an access.

It's not public because has it's still in design conception, everything can change from one day to another, and we don't want to support some kind of version or API.

Moreover, we are not in a hurry to release it and don't want to, so we won't fix a release date.

**Comment by qynybary-ryteto** [comment]
Hello @serpilliere,

Thank you for the update on `miasm-rs`. Could I request access to the this version? I have experience in Rust and substantial experience in reverse engineering and am keen to contribute to the project. I understand the need for confidentiality and am prepared for any changes in the project. You can reach me at qynybary_ryteto[@]protonmail[.]com for further discussion.

Thx
