### ISSUE TITLE
problem disassembling mips430 raw opcodes

### ISSUE THREAD

**Issue by aguilbau** [cea-sec/miasm#280]
Hi,

I think that the mips430 disassembler outputs erroneous assembly,
using the following code:
```
    container = Container.from_string(s)
    machine = Machine('msp430')
    mdis = machine.dis_engine(container.bin_stream)
    blocs = mdis.dis_multibloc(0)
    for b in blocs:
        print b
```
the intput 
```
s = '\x30\x41\x31\x40\x00\x00'
```
yields
```
loc_0000000000000000:0x00000000
mov.w      @SP+, PC
```
but the expected output is
```
loc_0000000000000000:0x00000000
mov.w      @SP+, PC
mov.w      0x0000, SP
```

**Comment by serpilliere** [comment]
Hi 

The disassembler engine tries to follow the execution flow. As the first instruction here is:
`mov.w      @SP+, PC` the execution flow is stopped, because we set PC to an unknown destination.

This instruction is a synonymous of `RET` (in x86) and as in x86, we don't known were to go after a `RET`.

**Comment by aguilbau** [comment]
Oh ok, I see ! Thanks for that explanation.

**Comment by aguilbau** [comment]
But then, is there a way to set up the stack for the dissasembly ? or to rebase the code, for the case of long jumps ?

**Comment by a-vincent** [comment]
Hi,

disassembly through this module is static, so the "value" of registers would have no impact on it.

Maybe you should use the jitter to follow the instruction flow if you want to.

Regards,
 Aymeric
