### ISSUE TITLE
Address resolution to procedure name (ELF)

### ISSUE THREAD

**Issue by Junraa** [cea-sec/miasm#338]
Hi,

I was just wondering if there was a built-in way to resolve address location (ones used as label/location when disassembling) to actual function name, without using any exterior help/traces/database ?
I went through all the code and I haven't found one yet.

Since I did not find anything, I tried something on my side, playing with information that elfesteem provide, by the _executable field in the ContainerELF class. It actually works as I want, but if there is any built-in way...

Thank you,

**Comment by serpilliere** [comment]
If I understand correctly: you want to rename Miasm's labels in the assembly listing using informations extracted from the *ELF*, right?
What do you mean be external help/databases? Do you consider *Elfesteem* as an exterior help?

**Comment by Junraa** [comment]
> If I understand correctly: you want to rename Miasm's labels in the assembly listing using informations extracted from the ELF, right?

By external, I meant any kind of output that some tools could compute.

Yes. I actually use Elfesteem and since miasm uses it, I do not consider it as an exterior help.

**Comment by commial** [comment]
Actually, to answer your question:
* from an external tool, parsing and loading symbol is left as an exercise to the user (using `symbool_pool`), because the API is already available (no hack needed, no simpler way are coming to my mind);
* from Elfesteem, it is currently missing. We can directly load known symbols from the `.symtab` while instantiating the `symbol_pool` object.

So, thanks you for reporting this!
I will add this behavior ASAP. Please drop a comment if I misunderstood your needs.
