### ISSUE TITLE
Less hacky way to install libtcc

### ISSUE THREAD

**Issue by fmonjalet** [cea-sec/miasm#36]
Hi,

I saw in the installation procedure that a patch to libtcc's `Makefile` is necessary to get it to compile with `-fPIC`. In fact, providing the `--disable-static` option to the `configure` script has the same effect.
So it might seem less hacky to do `./configure --disable-static && make && make install` rather than patching the `Makefile`. Does it work for you too?

Also, for LLVM, in Fedora (and probably other `yum` using linuces) the package is called `python-llvmpy`, if you want to add it.

Cheers!

Florent

**Comment by commial** [comment]
Hi,

You're *absolutely* right. The associated PR takes it in account, and I've also submitted a PR to the [Miasm-Docker installation](https://github.com/serpilliere/miasm-docker) project.

Regarding `pyLLVM`, the support will be likely soon dropped (see #5). That's why I haven't add a line in the `README`.

**Comment by commial** [comment]
#39 Merged. Thanks again.
