### ISSUE TITLE
TCC not found even if it's installed

### ISSUE THREAD

**Issue by peperunas** [cea-sec/miasm#444]
```
$ uname -r
4.7.6-1-ARCH

$ tcc -v
tcc version 0.9.26 (x86-64 Linux)

$ python decrypt.py test.exe
Traceback (most recent call last):
  File "decrypt.py", line 12, in <module>
    sb = Sandbox_Win_x86_32(filename, options, globals())
  File "/home/giulio/sec/ctf2/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 393, in __init__
    Sandbox.__init__(self, *args, **kwargs)
  File "/home/giulio/sec/ctf2/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 55, in __init__
    cls.__init__(self, **kwargs)
  File "/home/giulio/sec/ctf2/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 307, in __init__
    super(Arch_x86, self).__init__(**kwargs)
  File "/home/giulio/sec/ctf2/lib/python2.7/site-packages/miasm2/analysis/sandbox.py", line 155, in __init__
    self.jitter = self.machine.jitter(self.options.jitter)
  File "/home/giulio/sec/ctf2/lib/python2.7/site-packages/miasm2/arch/x86/jit.py", line 74, in __init__
    jitter.__init__(self, ir_x86_32(sp), *args, **kwargs)
  File "/home/giulio/sec/ctf2/lib/python2.7/site-packages/miasm2/jitter/jitload.py", line 217, in __init__
    raise RuntimeError('Unsupported jitter: %s' % jit_type)
RuntimeError: Unsupported jitter: tcc
```

I followed the installation instructions and everything went fine.
What am I missing?

**Comment by serpilliere** [comment]
Hi!

Have you flushed your library cache on your distribution after the `tcc` installation?
For exemple, on `Debian` :
```
ldconfig -v
```

And see if you have an entry like:
```
ldconfig:    libtcc.so.1.0 -> libtcc.so.1.0
```


Just for information:
Is your distribution ArchLinux?

**Comment by itsacoderepo** [comment]
Hi Krishath,

try to use gcc (works good for me on arch). This should help you: https://github.com/cea-sec/miasm/issues/399.

Best regards

**Comment by Krishath** [comment]
Thanks for your extremely fast responses!
@serpilliere yes I'm using Arch and I haven't that entry.
@itsacoderepo using gcc works.

What's the difference between these 4 options? (llvm, tcc, gcc and python)

Thanks again.

**Comment by commial** [comment]
This option set the engine used for JiTing the IR.
TCC and GCC relies on a external C compiler, the first one being entirely in memory but ignoring any optimisation on the Miasm generated C code.
LLVM is based on the JiT module of LLVM, with a first translation to the LLVM IR (but it is no more working due to a framework change).
Finally, the `python` one actually use the Miasm symbolic execution engine, but with concrete values for registers and memory accesses.

Due to the fact that the GCC outputs are optimised and cached in a temporary directory, it is the fastest engine when you have at least two run.
As TCC doesn't optimize anything (it is a so-called "one pass compiler"), it is the fastest on a code with a lot of basic block never seen before, at least during the first run.
The Python engine is useful for testing the symbolic execution against real binaries, for fast implementation of custom behavior (extending `EmulatedSymbExec`) and for running code with arbitrary element size (>64bits elements aren't available with TCC, >128bits elements aren't available with GCC).
And for LLVM, we will see when the move to the new framework will be effective.

**Comment by peperunas** [comment]
Thanks!
