### ISSUE TITLE
Instruction attributes (offset,l,b) not set when asm is parsed

### ISSUE THREAD

**Issue by jbcayrou** [cea-sec/miasm#548]
Hi !

I am currently implementing an architecture and I noticed some differencies between a bytecode disassembled and an asm parsed (_parse_asm.parse_txt_ function)

When bytecode is dissasembled, _dis_ method of _cls_mn_ is called

See file cpu.py, class 'cls_mn'
https://github.com/cea-sec/miasm/blob/master/miasm2/core/cpu.py#L1204-L1209
``` python
   @classmethod
    def dis(cls, bs_o, mode_o = None, offset=0):
	   [...]

            instr = cls.instruction(c.name, mode, c_args,
                                    additional_info=c.additional_info())
            instr.l = prefix_len + total_l / 8
            instr.b = cls.getbytes(bs, offset_o, instr.l)
            instr.offset = offset_o
            instr.get_info(c)
            if c.alias:
                alias = True
            out.append(instr)
            out_c.append(c)
```

In this case, intr.l intr.b and intr.offset are set.

However in the case where asm is parsed (with `parse_asm.parse_txt`), '_fromstring_' is called
https://github.com/cea-sec/miasm/blob/master/miasm2/core/cpu.py#L1301-L1303
``` python
    @classmethod
    def fromstring(cls, s, mode = None):
	 [...]

	instr = cls.instruction(c.name, mode, c_args,
		        additional_info=c.additional_info())

        return instr

```
Here 'offset' and 'l' attributes of cls.instruction are not set.

In my case I fixed the length by adding
```python
        instr.l = c.mn_len / 8
```
But I have no idea how to correctly set the offset attribute (unlike dis method, _fromstring_ is not called with 'offset' argument)

Another workaround I found is to build bytecode from asm and then disassemble it.

**Comment by serpilliere** [comment]
Hi!
The fact that those fields are not set when the objects comes from `fromstring` is normal.
When you come from this form (ie text assembly form), Miasm sends back the python object of the parsed instruction. And this instruction is not 'pinned' to a special form (yep), nor a special offset.

That's why those fields are not set.
If you absolutely need then, you have to "pin" then, ie assemble them at an arbitrary offset (same if you execute `parse_txt`)

This is because some instructions in some architecture have a byte form depending on these information. 

Don't hesitate if I am not clear in my explanations.

**Comment by jbcayrou** [comment]
Hi !
Thanks for your explainations, I will just "pin" them in my case :)
You can close the issue.
