### ISSUE TITLE
Support arm/armthumb switch or Not?

### ISSUE THREAD

**Issue by sparktend** [cea-sec/miasm#563]
When I used miasm to execute symbol with armthumb arch, I got an error. The error logs are here:
```
WARNING: cannot disasm at 3590
WARNING: cannot disasm at 3590
Traceback (most recent call last):
  File "target2.py", line 124, in <module>
    for bbl in asm_blocks: ira.add_bloc(bbl)
  File "/tools/miasm/miasm2/ir/ir.py", line 529, in add_bloc
    ir_blocks_all, gen_pc_updt)
  File "/tools/miasm/miasm2/ir/ir.py", line 502, in add_instr_to_irblock
    assignblk, ir_blocks_extra = self.instr2ir(instr)
  File "/tools/miasm/miasm2/ir/ir.py", line 418, in instr2ir
    ir_bloc_cur, extra_assignblk = self.get_ir(instr)
  File "/tools/miasm/miasm2/arch/arm/sem.py", line 1248, in get_ir
    instr_ir, extra_ir = get_mnemo_expr(self, instr, *args)
  File "/tools/miasm/miasm2/arch/arm/sem.py", line 1216, in get_mnemo_expr
    raise ValueError('unknown mnemo %s' % instr)
ValueError: unknown mnemo LDCMIL     p3, c9, [R8, 0xFFFFFFE0]!
```
The assembly code at 0x3590 is a jump table for switch. The code below it is **BL  __gnu_thumb1_case_uqi**.

The code is here:
```
bin_stream = bin_stream_str(bin_file)
mdis = machine.dis_engine(bin_stream)
asm_blocks = mdis.dis_multibloc(START_ADDR)
# Translate ASM -> IR
ira = machine.ira(mdis.symbol_pool)
for bbl in asm_blocks: ira.add_bloc(bbl)
```

The question is:
1. Does miasm support arm switch?
2. If the answer is 'Yes', What's wrong with me when I call the interface to execute symbol?

**Comment by serpilliere** [comment]
Hi!

Miasm has many `arm thumb` instructions, but does not have a lot of `thumb2` instructions implemented.

But in your case, Miasm managed to disassemble the instruction at 0x3590:
```
LDCMIL     p3, c9, [R8, 0xFFFFFFE0]!
```
So this is not the problem. The problem here is that it doesn't known the semantic of `LDCMIL` (this instruction's semantic is not implemented yet).

But this instruction seems a bit weird. Are you sure you have selected the correct endianess?
Can you provide the *bytes* at address 0x3590?
Do you have disassemble it with another disassembler?


Thanks!
