### ISSUE TITLE
wrmsr on x86_64

### ISSUE THREAD

**Issue by hlequien** [cea-sec/miasm#595]
Hello,

I was trying to make segment registers work on x86_64, I couldn't find a way to set the MSRT other than addding `wrmsr` at the beggining of the code. When doing so, tcc generated an error starting with
```
error: 'MSR' undeclared
Erreur de compilation !
```

I created a test case to reproduce the error and and joined the full error generated on my machine (tested with installed and fresh install).

Hope you can help, thank you.
[wrmsr.zip](https://github.com/cea-sec/miasm/files/1200987/wrmsr.zip)

**Comment by commial** [comment]
Hi @hlequien,

Two things here:
* I see in your code that you probably want to enable segment registers. In Miasm, there aren't activated through MSR, but directly in the jitter options. Please have a look at the `--usesegm` option implementation in [`Sandbox`](https://github.com/cea-sec/miasm/blob/master/miasm2/analysis/sandbox.py#L365) (to activate the support of segment) and to [`set_win_fs_0`](https://github.com/cea-sec/miasm/blob/master/miasm2/os_dep/win_api_x86_32_seh.py#L600) (to set it):
```Python
# Enable support
jitter.ir_arch.do_stk_segm = True
jitter.ir_arch.do_ds_segm = True
jitter.ir_arch.do_str_segm = True
jitter.ir_arch.do_all_segm = True

# Set a segm addr for the segment 4
fs = 4
jitter.cpu.FS = fs
jitter.cpu.set_segm_base(fs, tib_address)
```
* The error you get is because MSR are not emulated for now in Miasm; therefore, they exists in the semantic (to represent the instruction behavior), but are not implemented in the jitters. It should be  quite easy to add them; the hard part is about managing their effects on the CPU emulation. Currently, we do not have plan to support them in the near future. We enable or disable these behaviours using the Python objects

Hope it helps!

**Comment by hlequien** [comment]
Thank you for your help, it does the job !
Thank you again, I appreciate your work and your quick answer.

Have a good day.
