### ISSUE TITLE
Make disasmEngine._dis_block public

### ISSUE THREAD

**Issue by kenoph** [cea-sec/miasm#624]
Hi,
first of all, thanks for the amazing framework.

I recently used miasm to translate a VM's bytecode to IR. The dispatching was the usual:
```C
switch (opcode) {
  case 0: blabla(); break;
  case 1: asdasd(); break;
  ...
  default: qweqwe();
}
useless();
```

I had a problem because the default case was actually falling through without any jump so using `mdis.dis_block` also included all the stuff going on after the switch statement (`useless()`).

At first I hacked around it, but it was clear that the best solution was to use `mdis._dis_block` directly and giving it all the previously disassembled blocks.
Since I think this is a common scenario, IMHO `_dis_block` should be public API.
I would make a simple `s/_dis_block/dis_block/g` PR but I do understand that it would break retrocompatibility with basically anything else since `dis_block` is used often.

What are you thoughts?

EDIT: suppose also that `blabla` and `asdasd` take arguments calculated on the basic block before (or several blocks before) so I can't just execute the single opcode blocks.

**Comment by commial** [comment]
Hi @kenoph,
I'm not entirely sure to understand your use case, even if I appreciate the level of details you provided.

The differences between `dis_block` and `_dis_block` rely only on:
* giving the `job_done` internal structure (internal since https://github.com/cea-sec/miasm/pull/591)
* not returning the possible next offsets to disasm

From what you say, I understand that you want to use the `job_done` to stop disassembling the "default" BBL when it reachs the beginning of "useless" BBL, because you already had disasm "useless" and then you know its offset, that you put in `job_done` argument. Am I right?

As a side note, you may want to consider the `.dont_dis` or `split_dis` attributes: if an address (like "useless"'s offset) is in it, the disassembly engine will stop the current BBL and you will likely obtain the result you had with `_dis_block`.

**Comment by kenoph** [comment]
Yup, that's exactly what I need it for. I totally missed those attributes :/ Thanks.
