### ISSUE TITLE
Suggestion: Breakpoint before callback in runiter_once

### ISSUE THREAD

**Issue by roytu** [cea-sec/miasm#645]
**EDIT: This issue deals primarily with using `dse.attach()` in a breakpoint.  See @commial 's posts below.**

Maybe I'm using the library wrong but I think it's more natural to have the breakpoints handled before callbacks in `miasm2/jitter/jitload.py` (lines 303 onwards).  This is how it currently is:

    # Callback called before exec
    if self.exec_cb is not None:
        res = self.exec_cb(self)
        if res is not True:
            yield res

    # Check breakpoints
    old_pc = self.pc
    for res in self.breakpoints_handler.call_callbacks(self.pc, self):
        if res is not True:
            if isinstance(res, collections.Iterator):
                # If the breakpoint is a generator, yield it step by step
                for tmp in res:
                    yield tmp
            else:
                yield res
    ...
    # Run the bloc at PC
    self.pc = self.runbloc(self.pc)

Now, if you register a breakpoint at address `0x400000` like so:

    sb.jitter.add_breakpoint(0x400000, func)
    ...
    def func(jitter):
        dse.attach(jitter)
        dse.update_state_from_concrete()

Then this happens:
1. We enter `runiter_once` at `pc = 0x400000`.
2. The breakpoint trips, we attach the DSE and update state from concrete.  Here, concrete and symbolic engines match.
3. `runbloc(self.pc)` runs, modifying the concrete state and incrementing pc (to e.g. `pc = 0x400002`).  The symbolic and concrete engines don't match here.
4. On the next instruction, `self.exec_cb` points to the DSE's callback, which starts processing at `pc = 0x400002` (if it manages to even survive the `self._check_state()` call).

The core problem is that the concrete engine runs the instruction at `0x400000` but the symbolic engine does not.  After switching the order to breakpoints-before-callbacks, the drift issues go away.

Thoughts?

**Comment by commial** [comment]
Hello,

This is indeed a known behaviour of DSE `attach` method when used in a breakpoint.

Quick answer:
the test [DSEAttachInBreakpoint](https://github.com/cea-sec/miasm/blob/master/test/analysis/dse.py#L100) shows how to successfully attach the DSE in a breakpoint. A call to `jitter.exec_cb(jitter)` has to be done, for the exact reasons you mention.

Long answer:
Regarding the explanation behind, it is more about an arbitrary choice. We initially try to change this way of proceeding (in #600, which has now been updated to reflect the current behaviour). There is also another waiting PR on this stuff (#607), to remove the use of iterators and simplify this code snippet.

The problem is "how a user will intuitively think callback / breakpoints behave?". For instance:
* If the callback add a new breakpoint on the current PC, should the breakpoint be called?
* If a breakpoint modifies PC, should the next breakpoints on the same address be called?
* Should the DSE be called before the concrete execution or after?

For example, for the last question, we use the fact that no memory write have been done when the symbolic execution engine is called, so it can use the current state of the memory and do not conserve a "shadow memory".

Now, another solution is to complexify the method responsible for calling callback / breakpoints / `run_block`, to let it have several option, like callback before / after breakpoints, etc.
We try a version with a state machine to implement it, and it outs to be way too complicated to understand and maintain for a tiny benefit.
To let the user decide, we can also see the callback more as a wrapper than a callback inserted at a given point. This wrapper can then choose where and how it wants to call functions.
Actually, this is really close to an override of the aforementioned method, and it can becomes really tricky due to iterator supports (without having `yield from` in Python2...).

Its really tricky when it involve predicting how the user will think a thing behave. After discuting with @serpilliere and @WilliamBruneau, we end on keeping the current implementation, but being more explicit in help and comments on the actual behaviour of callback / breakpoints / block emulation.

Nevertheless, I'm really open to discussion if you have any thoughts on it.

**Comment by commial** [comment]
By the way, the conditions to call `exec_cb` are a bit complex, because its caller (`runiter_once`) has a few condition to be called, mainly due to optimization considerations.
It is called on `pc` when `pc` is the first address of a basic block, or an unknown address, or after an exception has been raised. To manage breakpoints inside a block, the block is split in two blocks to let `runiter_once` sees the breakpoint address during a run (it will be the first address of the second basic block).
As the imports simulation is done through custom addresses, there are unknown addresses, and then the breakpoint attached to them will be called.

Secondly, if the next block to call is already jitted, and there is no exception or anything else, Miasm will continue its execution without returning to Python, and then, without calling `runiter_once`. For instance, in a single basic block loop, it will be called once.
We think that users expect to have this callback being called for each loop iteration, so in the near future, setting an `exec_cb` will also force the jitter to avoid doing this "keep in the execution without going back to Python" optimization.

**Comment by roytu** [comment]
Hi commial, thanks for the detailed response.  Looks like a lot of thought went into this.  I think it'd be better if there were a way to communicate to the user that calling `attach()` in a breakpoint requires special handling, like having an optional function parameter (`attach(from_breakpoint=False)`) or a separate function (`attach_from_breakpoint()`) or even a note in the `DriftException` error.

Not sure if you also run the blog ([miasm.re](http://miasm.re)) but it'd be nice in the DSE posts to briefly mention this behavior, as I imagine it's a pretty common use case.

The `jitter.exec_cb(jitter)` line worked great, I've updated my original post a bit so maybe folks with the same issue will come across this.  Many thanks!

**Comment by commial** [comment]
I finally opted for #737, which is only a fix in documentation. Indeed, a `attach_from_breakpoint` API is not really a solution, because if there is a state update between the `attach` and the end of the breakpoint, the problem will remain. So, to avoid a solution which will be working only in a few case, I prefer warning the user about this code pattern, and give to it a tiny code template.
