### ISSUE TITLE
Can't build on windows

### ISSUE THREAD

**Issue by Youlor** [cea-sec/miasm#750]
My Environment: Windows10, Vistual Studio 2017
Error Log:
    creating build\temp.win-amd64-2.7\Release\miasm2\jitter
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\python27-x64\include -IC:\python27-x64\PC /Tcmiasm2/jitter/vm_mngr.c /Fobuild\temp.win-amd64-2.7\Release\miasm2/jitter/vm_mngr.obj
    vm_mngr.c
    miasm\miasm2\jitter\vm_mngr.h(196): error C2081: “__uint128_t”: The name in the parameter list is illegal.

That said, msvc complier don't support type: __uint128_t, so what should I do? Thanks!

**Comment by commial** [comment]
Hi Youlor,

msvc is not supported by Miasm (actually, there is no official support of
Miasm on Windows).
What you can try is using either clang, or WSL (Windows SubLinux)

**Comment by Youlor** [comment]
If I build it on Linux, Can I use it on Windows?

**Comment by commial** [comment]
I'm not sure to understand your question. You mean building the `.so` (ELF) files on Linux, and using them on Windows? That seems impossible to me outside the recent Linux subsystem on Windows.
Again, Windows is not officially supported, and probably needs additional digging. Thus, I can't give you more tips on it.

I'm closing the issue. If you have any additional information or a working setup for Windows, please, do not hesitate to re-open and share with us.

**Comment by serpilliere** [comment]
Hi!

I Just saw that someone (@TehRick) may have started some tests on windows:
https://github.com/TehRick/miasm/commit/3ab71ff0e6765f97aa8eed07322208596f70a475

Great :smile:

**Comment by TehRick** [comment]
Well the problems with VS2008 were:
- VS2008 std libs do not provide fpclassify, exp2 nor trunc.
- __attribute__((weak)) isn't standard
- designators in aggregate initializations are C99 / C++20
- SIG_ALERT does not exists on windows, so I used SetTimer to provide the vm timeout feature.
I have a local branch with a python 3 version of miasm (to compile C modules with VS2015), took me a week to take care of all str/bytes issues and pass all tests (also cleaned some stuff here and there).
I will have time in July to rebase and split the changes into incremental commits to propose clear pull requests.

**Comment by serpilliere** [comment]
Hi,
Great :smiley: 
For the Windows port, did you manage to run it natively or is it a work in progress?

For the python3: nice to hear this: we where starting thinking about it.
Oh, but something more:
We are actually preparing a *big* pull request, with a lot of modifications (we are adding a new word). So there is a *lot* of modified code, so maybe you should wait it for some rebase!

**Comment by TehRick** [comment]
Well, by "natively" if you mean on windows without the linux subsystem.. ofc since I am still on windows 7.
As far as I remember it was compiling and installing fine with py setup.py install, ready for PyPI.
Last year it worked with tcc, this year I only used it with the python jit and not extensively.
I will try llvm on windows + make it pass all tests and send a pull request ;)
Have fun with the big update !

**Comment by commial** [comment]
It's really nice to read that :)

To be honest, there is quite a few changes planned for the next weeks,
including the patch @serpi mentioned. If you have to add changes in many
code parts, I would recommend you to wait for these new changes to
stabilized, probably near August. We're trying to keep a changelog and some
versionning, so you may notice these changes.

Of course, do not hesitate if you have any question on Miasm.

**Comment by TehRick** [comment]
Well, by "natively" if you mean on windows without the linux subsystem.. ofc since I am still on windows 7.
As far as I remember it was compiling and installing fine with py setup.py install, ready for PyPI.
Last year it worked with tcc, this year I only used it with the python jit and not extensively.
I will try llvm on windows + make it pass all tests and send a pull request ;)
Have fun with the big update !
