### ISSUE TITLE
Bad phi generation in ssa transform?

### ISSUE THREAD

**Issue by serpilliere** [cea-sec/miasm#911]
Hi!

It seems there are strange `Phi` generated in some special graph.
Here is a script which generate a `graph.dot` and it's associated `ssa.dot`.
I wondered if the generate `Phi` for the `b` variable was normal.

Maybe @mrphrazer can help us?

Here is the script:
```python
from pdb import pm
from pprint import pprint as pp
from miasm2.expression.expression import ExprId, ExprInt, ExprAssign, ExprMem, \
    ExprCond
from miasm2.core.locationdb import LocationDB
from miasm2.analysis.data_flow import *
from miasm2.ir.analysis import ira
from miasm2.ir.ir import IRCFG, IRBlock, AssignBlock
from miasm2.analysis.ssa import SSADiGraph

loc_db = LocationDB()

a = ExprId("a", 32)
b = ExprId("b", 32)
c = ExprId("c", 32)
d = ExprId("d", 32)
r = ExprId("r", 32)
x = ExprId("x", 32)
y = ExprId("y", 32)

u8 = ExprId("u", 8)

pc = ExprId("pc", 32)
sp = ExprId("sp", 32)

CST0 = ExprInt(0x0, 32)
CST1 = ExprInt(0x1, 32)
CST2 = ExprInt(0x2, 32)
CST3 = ExprInt(0x3, 32)

CSTX_8 = ExprInt(0x25, 8)

LBL0 = loc_db.add_location("lbl0", 0)
LBL1 = loc_db.add_location("lbl1", 1)
LBL2 = loc_db.add_location("lbl2", 2)
LBL3 = loc_db.add_location("lbl3", 3)
LBL4 = loc_db.add_location("lbl4", 4)
LBL5 = loc_db.add_location("lbl5", 5)
LBL6 = loc_db.add_location("lbl6", 6)

IRDst = ExprId('IRDst', 32)
dummy = ExprId('dummy', 32)


def gen_irblock(label, exprs_list):
    irs = []
    for exprs in exprs_list:
        if isinstance(exprs, AssignBlock):
            irs.append(exprs)
        else:
            irs.append(AssignBlock(exprs))
    irbl = IRBlock(label, irs)
    return irbl


class Arch(object):

    def getpc(self, _):
        return pc

    def getsp(self, _):
        return sp

class IRATest(ira):

    """Fake IRA class for tests"""

    def __init__(self, loc_db=None):
        arch = Arch()
        super(IRATest, self).__init__(arch, 32, loc_db)
        self.IRDst = IRDst
        self.ret_reg = r

    def get_out_regs(self, xx):
        out = set()
        """
        for assignblk in xx:
            for dst in assignblk:
                if str(dst).startswith("r"):
                    out.add(dst)
        """
        out.add(r)
        return out

IRA = IRATest(loc_db)
END = ExprId("END", IRDst.size)


G9_IRA = IRA.new_ircfg()

G9_IRB0 = gen_irblock(LBL0, [
    [ExprAssign(IRDst, ExprLoc(LBL1, 32))]
])
G9_IRB1 = gen_irblock(LBL1, [
    [ExprAssign(b, CST1)],
    [ExprAssign(IRDst, ExprCond(x,
                                ExprLoc(LBL1, 32),
                                ExprLoc(LBL2, 32)
                                )
    )]
])
G9_IRB2 = gen_irblock(LBL2, [
    [ExprAssign(r, b)],
    [ExprAssign(IRDst, END)]
])

for irb in [G9_IRB0, G9_IRB1, G9_IRB2]:
    G9_IRA.add_irblock(irb)

ExprId.__repr__ = ExprId.__str__


open('graph.dot', 'w').write(G9_IRA.dot())
# SSA
head = LBL0
ssa = SSADiGraph(G9_IRA)
ssa.transform(head)
open("ssa.dot", "wb").write(ssa.graph.dot())
```

**Comment by serpilliere** [comment]
Here is the graph:
![graph](https://user-images.githubusercontent.com/9433661/50523099-8efd0c80-0ace-11e9-840b-719840b1ff04.png)
And the ssa version:
![ssa](https://user-images.githubusercontent.com/9433661/50523114-9b816500-0ace-11e9-8cb7-4cf24ade331c.png)

**Comment by commial** [comment]
Hey, not sure to understand your concern.
In lbl1, b can come from 2 different parent, so there is a phi. Why does it seem strange to you?

**Comment by commial** [comment]
OK, I understand. B should be dead entering lbl1 from lbl0 :) Sorry for the too quick answer

**Comment by serpilliere** [comment]
Yes this is exactly my question:
Is it "normal" for the algorithm to generate `phi` for such a variable?
If yes, no problem: as you said the `dead_simp` will remove this.
If no, maybe we can do a fix to avoid generating such an assignment.

**Comment by mrphrazer** [comment]
Hi!

This is a good example! Yes, based on the algorithm, this is intended behavior for this naive version of SSA. Why?  

Rephrasing @commial: since `lbl1`  is a self loop, it is basically part of its own dominance frontier. Therefore, we place a `phi` function for all variables in the block's frontier, including `b`.  In this case, we always assign `b` to the same constant value, which makes the `phi` function dea. It is some over approximation that has to happen _conceptually_; if we wouldn't place it, a slightly different assignment (e.g., `b = b + 0x1`) would distort the results. In other words, the algorithm works on the graph/dominance frontier level without performing liveness checks on the code level.

If we look at the implementation, the following two functions are important: 

1. [`_init_variable_defs`](https://github.com/cea-sec/miasm/blob/master/miasm2/analysis/ssa.py#L382) maps all variable definitions to basic blocks (in not particular order).
2.  [`_place_phi`](https://github.com/cea-sec/miasm/blob/master/miasm2/analysis/ssa.py#L408) places a variable for every basic block in the dominance frontier.

To tackle the overapproximation, more data flow logic has to be added somewhere around these places. There are many different SSA algorithms, some of them do exactly thinks like that. The [SSA book](http://ssabook.gforge.inria.fr/latest/book.pdf) is a good starting point.
