### ISSUE TITLE
ARM64: Implement instructions CASP, CASPA, CASPAL, CASPL

### ISSUE THREAD

**Issue by su-vikas** [cea-sec/miasm#920]
From Arm documentation: 

> Compare and Swap Pair of words or doublewords in memory loads a pair of 32-bit words or 64-bit doublewords from memory, and compares them against the values held in a first pair of registers. If the comparison is equal, the values in a second pair of registers are stored to memory.

**Comment by serpilliere** [comment]
Hi!
I am looking at this. The problem is that my aarch64 cross compilator doesn't want to eat them, so I cannot generate bits of those instructions for now. And I didn't put my hands on a binary with them.
Can you share some bytes of the encoded version of those instruction for testing purpose?

I mean not a whole binary, just the bytes may be sufficient.

**Comment by serpilliere** [comment]
Ho sorry for this: I managed to generate some :smile: 
Don't move.

**Comment by su-vikas** [comment]
Hi Fabrice, 

Really appreciate the quick turnaround time. 
Can I use the PR, or there are still some things to be fixed in it? I see some TODO's in the commit, so not sure.

**Comment by serpilliere** [comment]
You can: the commit are here to remember we may add memory barrier hint in the future, but in our case, there is no problem: the static code analysis of symbolic exec or emulation is mono core in Miasm for now !
But don't hesitate to tell me if there is a problem or if everything seems ok for you!
